---
# Almost all linters; some of them are optional.

linters-settings:
  depguard:
    rules:
      main:
        files:
        - $all
        - "!$test"
        deny:
          - pkg: errors
            desc: use "github.com/pkg/errors" instead

  goimports:
    local-prefixes: github.com/percona/percona-everest-cli

  unused:
    check-exported: true

  unparam:
    check-exported: true

  revive:
    rules:
      - name: if-return
        disabled: true
  gci:
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/percona/percona-everest-cli) # Groups all local imports.


linters:
  enable-all: true
  disable:
    - exhaustruct      # not useful
    - exhaustivestruct # annoying and duplicates exhaustruct
    - gomnd            # not useful
    - maligned         # deprecated, replaced by fieldalignment. We're ok wasting a couple bytes now
    - nlreturn         # too many empty lines makes methods too long
    - varnamelen       # it's useful sometime to have a one-letter name
    - wsl              # too many empty lines makes methods too long
    - wrapcheck        # forces to wrap errors everywhere
    - lll              # Just useless in the most cases


issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen       # tests may be long
        - testpackage  # senseless
