// Code generated by mockery v2.36.1. DO NOT EDIT.

package install

import (
	context "context"

	client "github.com/percona/percona-everest-backend/client"
	mock "github.com/stretchr/testify/mock"
)

// mockEverestClientConnector is an autogenerated mock type for the everestClientConnector type
type mockEverestClientConnector struct {
	mock.Mock
}

// CreateMonitoringInstance provides a mock function with given fields: ctx, body
func (_m *mockEverestClientConnector) CreateMonitoringInstance(ctx context.Context, body client.MonitoringInstanceCreateParams) (*client.MonitoringInstanceBaseWithName, error) {
	ret := _m.Called(ctx, body)

	var r0 *client.MonitoringInstanceBaseWithName
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.MonitoringInstanceCreateParams) (*client.MonitoringInstanceBaseWithName, error)); ok {
		return rf(ctx, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.MonitoringInstanceCreateParams) *client.MonitoringInstanceBaseWithName); ok {
		r0 = rf(ctx, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.MonitoringInstanceBaseWithName)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.MonitoringInstanceCreateParams) error); ok {
		r1 = rf(ctx, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMonitoringInstance provides a mock function with given fields: ctx, pmmInstanceID
func (_m *mockEverestClientConnector) GetMonitoringInstance(ctx context.Context, pmmInstanceID string) (*client.MonitoringInstanceBaseWithName, error) {
	ret := _m.Called(ctx, pmmInstanceID)

	var r0 *client.MonitoringInstanceBaseWithName
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*client.MonitoringInstanceBaseWithName, error)); ok {
		return rf(ctx, pmmInstanceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.MonitoringInstanceBaseWithName); ok {
		r0 = rf(ctx, pmmInstanceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.MonitoringInstanceBaseWithName)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pmmInstanceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListMonitoringInstances provides a mock function with given fields: ctx
func (_m *mockEverestClientConnector) ListMonitoringInstances(ctx context.Context) ([]client.MonitoringInstanceBaseWithName, error) {
	ret := _m.Called(ctx)

	var r0 []client.MonitoringInstanceBaseWithName
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]client.MonitoringInstanceBaseWithName, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []client.MonitoringInstanceBaseWithName); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]client.MonitoringInstanceBaseWithName)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetKubernetesClusterMonitoring provides a mock function with given fields: ctx, body
func (_m *mockEverestClientConnector) SetKubernetesClusterMonitoring(ctx context.Context, body client.KubernetesClusterMonitoring) error {
	ret := _m.Called(ctx, body)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, client.KubernetesClusterMonitoring) error); ok {
		r0 = rf(ctx, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockEverestClientConnector creates a new instance of mockEverestClientConnector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockEverestClientConnector(t interface {
	mock.TestingT
	Cleanup(func())
},
) *mockEverestClientConnector {
	mock := &mockEverestClientConnector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
