---
name: CLI tests
on:
  push:
    branches:
      - fix-deps

jobs:
  integration_tests:
    name: CLI ${{inputs.make_target}}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      # no `-mod=readonly` to test PRs made by @dependabot;
      # `git diff --exit-code` step below still checks what we need
      GOPRIVATE: github.com/percona,github.com/percona/percona-everest-backend,github.com/percona/everest-operator
      PERCONA_VERSION_SERVICE_URL: https://check-dev.percona.com/versions/v1
      MAKE_TARGET: ${{ inputs.make_target }}
    steps:
      - name: Configure git for private modules
        env:
          ROBOT_TOKEN: ${{ secrets.ROBOT_TOKEN }}
        run: git config --global url."https://percona-platform-robot:${ROBOT_TOKEN}@github.com".insteadOf "https://github.com"

      - name: Set up Go release
        uses: percona-platform/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set GO_VERSION environment variable
        run: |
          go version
          echo "GO_VERSION=$(go version)" >> $GITHUB_ENV

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          lfs: true
          ref: ${{ github.event.pull_request.head.sha }}


      # https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources
      # https://minikube.sigs.k8s.io/docs/drivers/docker/
      - name: Configure minikube
        working-directory: cli-tests
        run: |
          minikube delete --all --purge
          rm -rf ~/.minikube
          minikube config set cpus 2
          minikube start

      - name: Set up Go release for CLI
        uses: percona-platform/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build CLI binary
        run: |
          make init
          make build

      - name: Configure git for private modules
        env:
          ROBOT_TOKEN: ${{ secrets.ROBOT_TOKEN }}
        run: git config --global url."https://percona-platform-robot:${ROBOT_TOKEN}@github.com".insteadOf "https://github.com"

      - name: Run ${{ env.MAKE_TARGET }} integration tests
        working-directory: cli-tests
        id: cli-tests
        run: |
          make init
          make ${{ env.MAKE_TARGET }}

      - name: Collect logs from backend
        if: ${{ always() && steps.cli-tests.outcome != 'success' }}
        working-directory: cli-tests
        run: 'echo "here should be a command to extract and save backend logs"'

      - name: Attach the report
        if: ${{ always() && steps.cli-tests.outcome != 'skipped' }}
        uses: actions/upload-artifact@v3
        with:
          name: test-delete-cluster-tests-report
          path: cli-tests/test-report
